### ISSUE TITLE
[FEATURE REQUEST] Show Description

### ISSUE THREAD

**Issue by Kayinwonderland** [grinstantin/todoist-card#13]
Hey and thank you for this great card!

We Are using Todoist to show  what we have stored in our fridge (A weird way, I know)
In the description we have added in what shelf we have it stored. Would it be possible to somehow show the description Text as well?

Have a great day
Kati

**Comment by grinstantin** [comment]
Hi!

Added item description to the card in [1.0.9.1](../releases/tag/v1.0.9.1):

![image](https://user-images.githubusercontent.com/34913257/185072926-071c9d94-eef5-4937-9c10-38a6ea3c1a3d.png)

Closing this issue, but if there will be any questions about this - feel free to reopen it.
