### ISSUE TITLE
[BUG] Card doesn't allow submit a new item when we have more than one list

### ISSUE THREAD

**Issue by MiguelCosta** [grinstantin/todoist-card#19]
**Before submitting a bug**
- [X] I updated to the latest card version available
- [X] I cleared the cache of my browser

**Describe the bug**
I have two list: Todo list and Shopping list, but when I try to add something in the first list, the keyboard doesn't show the submit button.

This occurs using different keyaboards or diferent android versions.

**To Reproduce**
1. Go to the first list and try to add a new item
2. THe leyboard only show the "next" key.

**Expected behavior**
Should be possible add a new item in the first list.

**Screenshots**

First list:

![image](https://user-images.githubusercontent.com/645482/198245372-68bcd06e-e170-4374-9445-140e7c348a4b.png)

Second list:

![image](https://user-images.githubusercontent.com/645482/198245466-d8b02ff6-1640-457e-8926-30334aad63a3.png)

Video:

https://user-images.githubusercontent.com/645482/198244902-c2cb6924-8de5-4e85-a3e3-bc0c0d61adc5.mp4

**Versions:**
 - Card: 1.1.1
 - HomeAssistant: 2022.10.5
 - Browser: Google Chrome on Android 13

**Additional context**
N/A

**Comment by grinstantin** [comment]
Merged #20, thank you!

**Comment by MiguelCosta** [comment]
@grinstantin thanks for this card! It is very usefull to me to integrate the Alexa Shopping List with the HA 🙂
Good job 💪
