### ISSUE TITLE
Have to refresh page for card to show

### ISSUE THREAD

**Issue by craigs66** [grinstantin/todoist-card#2]
I'm not sure if "I'm doing it wrong", but to get the Todist Card to display within Lovelace - Mac Chrome browser I have to refresh the page. When loading on a Fire Tablet, the card never displays because when I refresh the page, the main page is loaded vs the tab where I have the Todist Card programmed. The tab is then just blank.

**Comment by grinstantin** [comment]
Hello! Sorry for the late reply - for some reason I didn't get a new issue notification.
What version of the card are you using? Was this version originally installed, or did you update the card via HACS?

**Comment by craigs66** [comment]
I installed via HACS this past week.

**Comment by grinstantin** [comment]
Unfortunately, I've not been able to reproduce this error. The problem is most likely related to your browser's cache.
