### ISSUE TITLE
[BUG] I don't see a sensor.to_do_list to add as an entity

### ISSUE THREAD

**Issue by Lxxrxns** [grinstantin/todoist-card#24]
**Before submitting a bug**
- [x] I updated to the latest card version available
- [x] I cleared the cache of my browser

Hi! No matter what I tried, I can't see the to_do_list entity. Do I need to define this somewhere?

My configuration.yaml looks like this:

> calendar:
>   - platform: todoist
>     token: !secret todoist_api_token
> 
> sensor:
>   - platform: rest
>     name: To-do List
>     method: GET
>     resource: 'https://api.todoist.com/sync/v9/projects/get_data'
>     params:
>       token: !secret todoist_api_token
>       project_id: 2304083282
>     value_template: '{{ value_json[''project''][''id''] }}'
>     json_attributes:
>       - project
>       - items
>     scan_interval: 30
> 
> rest_command:
>   todoist:
>     method: post
>     url: 'https://api.todoist.com/sync/v9/{{ url }}'
>     payload: !secret todoist_api_payload
>     content_type: 'application/x-www-form-urlencoded'

**Comment by grinstantin** [comment]
Hi! Did you try to restart your HA?

**Comment by Lxxrxns** [comment]
Yeah! I tried everything... I ended up switching to the built-in shopping-cart as a to-do list which suits my needs :-#

**Comment by grinstantin** [comment]
And there are no related to Todoist errors in HA logs?

**Comment by Lxxrxns** [comment]
I'm guessing it has to do with this?

https://github.com/home-assistant/core/issues/79216#issuecomment-1354055769

**Comment by grinstantin** [comment]
No, I don't think so. This card is using Todoist's Sync API and has nothing in common with HA Todoist integration.

**Comment by grinstantin** [comment]
But, maybe, problems with that integration are causing problems with REST sensor used in this card.

**Comment by sdholden28** [comment]
I can confirm the same issue with my installation, on 2022.12.0. I've had this card working for a long time. A couple of months ago, it stopped working and I had to update the code to use v9 instead of v8 and it started working again. It has now stopped again as of 3 or 4 days ago. I've incorporated changes from the recent rest command updates, but no change.

**Comment by sdholden28** [comment]
Sensor is actually present, but shows a status of unknown since December 22, around 3:25am CST

**Comment by sdholden28** [comment]
https://github.com/grinstantin/todoist-card/issues/28#issuecomment-1366041493

**Comment by grinstantin** [comment]
I'm closing this issue, if the problem is still present - feel free to open it again.
