### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by sphirst** [grinstantin/todoist-card#28]
**Before submitting a bug**
- [Yes] I updated to the latest card version available
- [Yes] I cleared the cache of my browser

**Describe the bug**
All cards are showing "no uncompleted tasks" even though there are tasks in the todoist app

**Expected behavior**
I should be able to see tasks to be completed

**Versions:**
 - Card: [e.g. 1.1.2]
 - Home Assistant 2022.12.8
    Supervisor 2022.11.2
    Operating System 9.4
    Frontend 20221213.1 - latest
- Chrome Version 108.0.5359.125 (Official Build) (64-bit)

**Comment by sdholden28** [comment]
I've turned on debug logging for homeassistant.components.rest and found the following in the logs. I will double check my configuration to make sure I haven't introduced a typo.

2022-12-27 10:40:36.866 DEBUG (MainThread) [homeassistant.components.rest.data] Updating from https://api.todoist.com/sync/v9/projects/get_data
2022-12-27 10:40:39.065 DEBUG (MainThread) [homeassistant.components.rest.sensor] Data fetched from resource: {"error":"Invalid format for Authentication header","error_code":412,"error_extra":{"access_type":"none","event_id":"675480258f584a2a8e778fe621a0b5be","retry_after":1280},"error_tag":"AUTH_INVALID_AUTHENTICATION_HEADER","http_code":403}

**Comment by sdholden28** [comment]
I have resolved my issue. The key for me was a new format for the API token, which I had missed in the documentation updates. I don't know when this changed exactly, but I'm sure it was recently and it what broke my installation. I am also quite certain that many will miss this change, as its easy to miss. It should be highlighted somewhere in the documentation, although it is currently present. Your todoist_api_token MUST contain the word "Bearer" before your token ID and the whole thing MUST be included in single quotes, as shown below. Again, this is in the documentation as of 3 days ago, but its not marked as a change from previous and is easy to miss. This is what was causing my authentication error and preventing data from loading.

Example from secrets.yaml:

todoist_api_token: 'Bearer TODOIST_API_TOKEN'

**Comment by sphirst** [comment]
> I have resolved my issue. The key for me was a new format for the API token, which I had missed in the documentation updates. I don't know when this changed exactly, but I'm sure it was recently and it what broke my installation. I am also quite certain that many will miss this change, as its easy to miss. It should be highlighted somewhere in the documentation, although it is currently present. Your todoist_api_token MUST contain the word "Bearer" before your token ID and the whole thing MUST be included in single quotes, as shown below. Again, this is in the documentation as of 3 days ago, but its not marked as a change from previous and is easy to miss. This is what was causing my authentication error and preventing data from loading.
> 
> Example from secrets.yaml:
> 
> todoist_api_token: 'Bearer TODOIST_API_TOKEN'

You are a hero. This worked, thank you.

**Comment by grinstantin** [comment]
@sdholden28, check #25. I'll make an empty release to notify everyone about changes later.
