### ISSUE TITLE
Only from Todoist to Home Assistant - HA card read only?

### ISSUE THREAD

**Issue by dannymertens** [grinstantin/todoist-card#3]
**Before submitting a bug**
- [ Yes] I updated to the latest card version available
- [ Yes] I cleared the cache of my browser

**Describe the bug**
Well to be honest I don't know if its a bug, maybe I'm missing something but it looks like the HA card is some kind of read only for me?

**What's working**

I add a task in a project in the todoist webportal and after the scan (30 seconds) the task is displayed in my HA card
I check a task complete in the todoist webportal and the task is also checked off in the HA card

**What's not working**

- Adding task in HA card does nothing
- Checking a task off in HA card does nothing
- Deleting a task in HA does nothing

So it looks like the HA card is read only for me, is this correct behavior?

**To Reproduce**

Added this video hopefully that makes things clear?

https://youtu.be/JuPu_lWaPjQ

If not please don't hesitate to contact me!

**Expected behavior**
Use the hA card to update the task in the toist portal, add new items to the task list in todoist

**configuration.yaml**

_under sensors_

![image](https://user-images.githubusercontent.com/46963011/115956724-b594ac00-a4fe-11eb-85d6-799f46036f90.png)

_under rest command_

![image](https://user-images.githubusercontent.com/46963011/115956733-c9401280-a4fe-11eb-8972-bd1980942a41.png)

_secrets file_

![image](https://user-images.githubusercontent.com/46963011/115956757-ebd22b80-a4fe-11eb-9a53-dc0360f042b5.png)

_sensor development environment_

![image](https://user-images.githubusercontent.com/46963011/115956857-8894c900-a4ff-11eb-8986-004f77f656d5.png)

**Versions:**
 - Card: [v1.0.5]
 - HomeAssistant: 

Versie | core-2021.4.6
-- | --
Type installatie | Home Assistant OS
Ontwikkeling | false
Supervisor | true
Docker | true
Virtuele omgeving | false
Python-versie | 3.8.7
Besturingssysteemfamilie | Linux
Versie van het besturingssysteem | 5.9.16
CPU-architectuur | aarch64
Tijdzone | Europe/Brussels

 - Browser: [Chrome Mac: Version 90.0.4430.85 (Official Build) (x86_64)] [latest HA app iOs (latest version)]

**Additional context**
Maybe this is the issue, I have a free account will updating to pro fix this?

**Comment by grinstantin** [comment]
Good day! Thank you for provided info. You just forgot to replace one `TODOIST_API_TOKEN` in `secrets.yaml`.

**Comment by dannymertens** [comment]
Ok that's was just stupid off me, thanks for your quick reply and apologies for my stupidity!!

**Comment by grinstantin** [comment]
There is nothing "stupid" at all, glad I could help. Good luck!
