### ISSUE TITLE
Not working in HA 2023.3.5

### ISSUE THREAD

**Issue by Malvazar** [grinstantin/todoist-card#35]
I've tired installing this with both HACS and manually, but neither method work.
Everything is configured and what not, but the card just dose not show up in loveless. Tried clearing cookies and restarting HA multiple times, even tried creating the card manually, it simply just dose not exist for me.

**Comment by Malvazar** [comment]
Okay.... Randomly after 14 hours it just magically shows up in loveless. It's still broken for me though, its not showing any of my task from my todoist project I linked to.

**Comment by miniksa** [comment]
I thought I was having the same problem here and then I realized that my configuration was out of date. I had to very carefully re-copy the configuration changes here: https://github.com/grinstantin/todoist-card/commit/b5e0e85518e94943215ff83b3c2167899d004444

Changing my secret to a string containing "Bearer <token>" and updating all the URLs and moving the Authorization around was very important to getting this working again for me on HA 2023.3.6.

**Comment by Malvazar** [comment]
It was indeed the "Bearer" part that I was missing. Thanks for the help!

**Comment by churtbeullar** [comment]
Hi.
I have the same problem, but I´m tripple checked the "Bearer" part. Requested a new token etc. I cant find anything that is wierd. Does anyone have an idéa what to check? I get the calenders integrated via the HA supported integration and the updated properly.

**Comment by churtbeullar** [comment]
> Hi. I have the same problem, but I´m tripple checked the "Bearer" part. Requested a new token etc. I cant find anything that is wierd. Does anyone have an idéa what to check? I get the calenders integrated via the HA supported integration and the updated properly.

As always, when you tried different solutions in a couple of hours and beg for help, problems are solving. The problem was that I wrote the entire project name instead of ID. For example: https://todoist.com/app/project/test-2317999586 remove "test-" and only keep the numbers.

**Comment by M-See** [comment]
> > Hi. I have the same problem, but I´m tripple checked the "Bearer" part. Requested a new token etc. I cant find anything that is wierd. Does anyone have an idéa what to check? I get the calenders integrated via the HA supported integration and the updated properly.
> 
> As always, when you tried different solutions in a couple of hours and beg for help, problems are solving. The problem was that I wrote the entire project name instead of ID. For example: https://todoist.com/app/project/test-2317999586 remove "test-" and only keep the numbers.

True.. I also faced the problem and struggled to get it running. Please fix the description for this integration to make it more precise.

Thanks!

**Comment by grinstantin** [comment]
Thank you for your feedback! Made token and project ID replacement clearer.
