### ISSUE TITLE
[BUG] No longer works with current Todoist integration

### ISSUE THREAD

**Issue by SarcasticShrimp** [grinstantin/todoist-card#48]
**Before submitting a bug**
- [Y ] I updated to the latest card version available
- [ Y] I cleared the cache of my browser

**Describe the bug**
The current implementation of the Todoist integration does not expose sensors (what this card is looking for) but rather exposes a Calendar entity and a Todo Entity for each todoist project.  
If you try to set this card's entity attribute to the todo entity (ex:   entity: todo.house_chores ), then the card just shows "No uncompleted tasks!" even though there are uncompleted items (for today) on the project/list in Todoist.

**Versions:**
 - Card: v1.1.3
 - HomeAssistant: 2023.12.1
 - Browser: Thorium Version 117.0.5938.157 (Official Build) (64-bit)

**Screenshots**
Project in Todoist showing incomplete items:
![House Chores – Todoist](https://github.com/grinstantin/todoist-card/assets/12154878/0ea09aee-8549-4b1b-be49-9c0b6f6bccc1)
Card showing configuration an resulting empy list:
![Todoist_Card](https://github.com/grinstantin/todoist-card/assets/12154878/7e838e3b-2aef-4cd6-899d-daaa52d4e549)
Entities exposed by Todoist integration:
![Todoist_Integration_Entities](https://github.com/grinstantin/todoist-card/assets/12154878/03bdee6e-bf44-4e94-94e8-fea46a2ef632)

**Comment by grinstantin** [comment]
Hey! This card was never supposed to work with Todoist HA integration, only through Todoist API (as described in [this section](https://github.com/grinstantin/todoist-card?tab=readme-ov-file#using-the-card)). You should use the default `todo-list` card for your `todo.house_chores`:

```yaml
- type: todo-list
  entity: todo.to_do
```
