### ISSUE TITLE
[FEATURE REQUEST] Compact view for showing a shopping list on a read-only dashboard (or custom CSS)

### ISSUE THREAD

**Issue by ndbroadbent** [grinstantin/todoist-card#5]
**Is your feature request related to a problem? Please describe.**

I have a dashboard screen in my kitchen where I would like to show our grocery list. We use Alexa to add groceries to the list, and then sync this with Todoist.

I like that I can disable some of the UI features for this card, but the buttons are still adding a lot of padding (even though they are invisible). This is taking up too much vertical space:

<img width="512" alt="Screen Shot 2021-11-18 at 1 36 54 PM" src="https://user-images.githubusercontent.com/139536/142317549-21564ecd-e969-4515-a7c5-2c26196ff029.png">

**Describe the solution you'd like**

Compact view without too much padding. I modified some CSS in the developer tools to get this:

<img width="501" alt="Screen Shot 2021-11-18 at 1 36 19 PM" src="https://user-images.githubusercontent.com/139536/142317143-35deceef-65e2-4365-816c-5de5bb263d8e.png">

**Describe alternatives you've considered**

I'm going to create a fork but my version will probably be a bit of a quick hack for now. If I implement this cleanly would you consider merging a PR? (No worries if you're too busy, I totally understand how GitHub projects can become really annoying to maintain. Happens to me a lot!)

**Comment by ndbroadbent** [comment]
Got it working nicely over here: https://github.com/ndbroadbent/todoist-compact-display-card

![image](https://user-images.githubusercontent.com/139536/142333819-856f4f3b-a202-4d80-bc12-f920987ea1f5.png)

It's a bit of a hack. Maybe we can just leave it like this and people can easily install the forked repo in HACS if they want

**Comment by grinstantin** [comment]
Hey, @ndbroadbent! This already happens when you disable the `show_item_close` option - [buttons](https://i.imgur.com/P2lZuSf.png) are changing to [icons](https://i.imgur.com/t6BP7Ql.png). In your case the icons are not loading for some reason. Were there any errors in your browser's developer console?

**Comment by grinstantin** [comment]
Since there is no new information on this issue, I'm closing it for now. @ndbroadbent, you can reopen it if needed.
