### ISSUE TITLE
only_today_overdue: true is displaying only overdue

### ISSUE THREAD

**Issue by AndrewsBrewing** [grinstantin/todoist-card#6]
**Describe the bug**
When using the card with the above attribute, the card only displays overdue items not what is due today.

**My configuration.yaml:**
sensor:
  - platform: rest
    name: To-do List
    method: GET
    resource: 'https://api.todoist.com/sync/v8/projects/get_data'
    params:
      token: !secret todoist_api_token
      project_id: MYPROJECTID
    value_template: '{{value_json[''project''][''id'']}}'
    json_attributes:
      - items
    scan_interval: 30

rest_command:
  todoist:
    method: post
    url: 'https://api.todoist.com/sync/v8/sync'
    payload: !secret todoist_api_payload
    content_type: 'application/x-www-form-urlencoded'

**Versions:**
 - Card: [1.0.7]
 - HomeAssistant: [2021.11.5]
 - Browser: [Google Chrome 96.0.4664.45]

**Comment by AndrewsBrewing** [comment]
I'm looking at your line 393.  I am in the New York Eastern Daylight Savings time zone.

**Comment by grinstantin** [comment]
Should be fixed in [1.0.8](../releases/tag/v1.0.8). Check it, please.
